---
title: "Assignment 3 - Hurricane Andrew"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE}
pacman::p_load(tidyverse,
               drat,
               hurricaneexposuredata,
               hurricaneexposure,
               weathermetrics)

addRepo("geanders")

data("hurr_tracks")
data("rain")

#head(hurr_tracks,15)
#head(rain, 15)
```


```{r}
#function to grab data from only Aug 16 - 28 (Andrew's course)
clean_dates <- function(station){
  station <- station %>% filter(MM == 8)
  station <- station %>% filter(DD >= 16 & DD <= 28)
}
```

Read the buoy data  
```{r}
#southern florida 
stmlrf1 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=MLRF1&year=1992&f1=wdir&t1a=gt&v1a=1&t1b=&v1b=&c1=and&f2=wtmp&t2a=gt&v2a=1&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

#florida keys
stsmkf1 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=SMKF1&year=1992&f1=wdir&t1a=gt&v1a=1&t1b=&v1b=&c1=and&f2=wtmp&t2a=gt&v2a=1&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

#bahamas
st41016 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=41016&year=1992&f1=wspd&t1a=ge&v1a=1&t1b=&v1b=&c1=and&f2=wtmp&t2a=ge&v2a=1&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

#east gulf
st42003 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=42003&year=1992&f1=wspd&t1a=ge&v1a=1&t1b=&v1b=&c1=and&f2=wtmp&t2a=ge&v2a=1&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

#west gulf
stbusl1 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=BUSL1&year=1992&f1=wspd&t1a=gt&v1a=1&t1b=&v1b=&c1=&f2=&t2a=&v2a=&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

stgbcl1 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=GBCL1&year=1992&f1=wspd&t1a=gt&v1a=1&t1b=&v1b=&c1=&f2=&t2a=&v2a=&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

##near texas
st42002 <- clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=42002&year=1992&f1=wspd&t1a=gt&v1a=1&t1b=&v1b=&c1=&f2=&t2a=&v2a=&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))

st42019 <-  clean_dates(read.table(url("https://www.ndbc.noaa.gov/histsearch.php?station=42019&year=1992&f1=wspd&t1a=gt&v1a=1&t1b=&v1b=&c1=&f2=&t2a=&v2a=&t2b=&v2b=&c2=&f3=&t3a=&v3a=&t3b=&v3b=&mode=data"), skip = 2, header = TRUE))
```

```{r}
#unfortunately, having to manually input coordinates from the website
coordmlrf1 <- c(x = -80.376, y = 25.012) #25.012N 80.376W
coordsmkf1 <- c(x = -81.109, y = 24.628) #24.628N 81.109W

coord41016 <- c(x = -76.5, y = 24.600) #24.600N 76.5W

coord42003 <- c(x = -85.615, y= 25.925) #25.925N, 85.615W 

coordbusl1 <- c(x = -90.9, y = 27.883) #27.883N 90.9W
coordgbcl1 <- c(x = -93.1, y = 27.800) #27.800N 93.1W

coord42002 <- c(x = -93.646, y = 26.055) #26.055N 93.646W
coord42019 <- c(x = -95.345, y = 27.910) #27.910N 95.345W
buoys <- data.frame(cbind(rbind(coordmlrf1, coordsmkf1, coord41016, coord42003,
                          coordbusl1, coordgbcl1, coord42002, coord42019), 
                    "buoy" = c("MLRF1", "SMKF1", "41016", "42003", "BUSL1", 
                                  "GBCL1", "42002", "42019")))
buoys$x <- as.numeric(buoys$x)
buoys$y <- as.numeric(buoys$y)
```

```{r}
#gather andrew path data
andrew_path <- hurr_tracks %>% filter(storm_id == "Andrew-1992")
andrew_path <- andrew_path %>% filter(longitude <= -60)
```


```{r}
#create a map

#get the east coast map from default_map() function
map_base <- default_map()
map_base <- map_base$data

#create ggplot
ggplot(map_base, aes(long, lat)) + 
  geom_polygon(aes(group = group), colour="black", fill = NA) + #base map
  geom_path(data = andrew_path, aes(x = longitude, y = latitude), color = "red") + #andrew's path 
  geom_point(data = buoys, aes(x = x, y = y, color = buoy)) + #buoys
  xlab("Longitude") + ylab("Latitude") + 
  ggtitle("Hurricane Andrew's path and nearby buoys") + 
  theme_bw()

```


##Miscellaneous functions provided to us 
```{r, eval = FALSE}
hmapper <- function(hurr){
    
    rmap = map_counties(storm = hurr, metric = "rainfall") +
            ggtitle(hurr) +
            theme(plot.title = element_text(hjust = 0.5))

    wmap = map_counties(storm = hurr, metric = "wind") +
            ggtitle(hurr) +
            theme(plot.title = element_text(hjust = 0.5))

    expos = map_rain_exposure(storm =hurr, 
                  rain_limit = 175, 
                  dist_limit = 500, 
                  days_included =-5:3) +
                    ggtitle(hurr) +
                    theme(plot.title = element_text(hjust = 0.5))

    ml <-  list(rmap, wmap, expos)
    names(ml) <- c("rmap", "wmap", "expos")
    
    return(ml)
}
 
mapps <- hmapper("Andrew-1992") 


mapps$rmap
mapps$wmap
mapps$expos
```

```{r, eval = FALSE}
map_counties(storm = "Andrew-1992", metric= "wind", days_included = -5:5) +
    ggtitle("Wind Andrew")

map_counties(storm = "Andrew-1992", metric = "rainfall", days_included = -5:5) +
    ggtitle("rain Andrew")

map_counties(storm = "Andrew-1992", metric= "rainfall", days_included = -1:0) +
    ggtitle("Rain Andrew") #rainfall
```